version: "3.3"
services:
  blockly_production:
    container_name: blockly_production_server
    image: tomneutens/blockly_production_server
    restart: always
    ports:
      - "12033:12032"
    networks:
      - docker
    volumes:
      - /var/environments:/var/environments
  mongodb:
    container_name: mongodb_server
    image: mongodb_server
    restart: always
    networks:
      - docker
    volumes:
      - mongodb_data_container:/data/db
networks:
  docker:
volumes:
  mongodb_data_container:
    labels:
      org.dwengo.description: "Mongodb data"