FROM node:18.17

# More info https://stackoverflow.com/a/55578829/13057688

ARG JENKINSUID
ARG JENKINSGID
ARG DOCKERGID

# Install puppeteer dependencies
RUN apt-get update && apt-get install -y iputils-ping chromium tree nano curl sudo ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

# Install Docker in the image, which adds a docker group
RUN apt-get -y update && \
 apt-get -y install \
   apt-transport-https \
   ca-certificates \
   curl \
   gnupg \
   lsb-release \
   software-properties-common

RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN chmod a+r /etc/apt/keyrings/docker.gpg
RUN echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get -y update && \
 apt-get -y install \
   docker-ce \
   docker-ce-cli \
   containerd.io

# Change node default group and user id since it conflicts with jenkins
RUN groupmod -g 1010 node
RUN usermod -u 1011 node

# Setup users and groups
RUN echo ${JENKINSGID}
RUN echo ${JENKINSUID}
RUN echo ${DOCKERGID}
RUN cat /etc/group
RUN groupadd -g ${JENKINSGID} jenkins
RUN groupmod -g ${DOCKERGID} docker
RUN cat /etc/passwd
RUN cat /etc/group
RUN useradd -c "Jenkins user" -g ${JENKINSGID} -G ${DOCKERGID} -M -N -u ${JENKINSUID} jenkins

# create default home directory for jenkins user
RUN mkdir /home/jenkins
#COPY hub_params.env /home/jenkins/env/hub_params.env
RUN chown -R jenkins:jenkins /home/jenkins 