pipeline {
    agent {
        dockerfile {
            filename 'jenkins/Dockerfile.jenkinsAgent'
            additionalBuildArgs  '--build-arg JENKINSUID=`id -u jenkins` --build-arg JENKINSGID=`id -g jenkins` --build-arg DOCKERGID=`stat -c %g /var/run/docker.sock`'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u jenkins:docker -p 3000:3000'
        }
    }
    stages {
        stage('Clone') { 
            steps {
                sh 'pwd'
                sh 'ls -al'
                sh 'rm -Rf blockly_repo'
                sh 'mkdir blockly_repo'
                sh 'cd blockly_repo' 
                sh 'git clone --single-branch --branch develop https://github.com/dwengovzw/Blockly-for-Dwenguino.git ./blockly_repo'
            }
        }
        stage('Build') { 
            steps {
                sh 'cd blockly_repo && npm install --legacy-peer-deps' 
            }
        }
        stage('Test') { 
            steps {
                sh 'cp blockly_repo/environments/test.env blockly_repo/.env'
                sh 'ls -al'
                sh 'cd blockly_repo && npm run test' 
            }
        }
    }
}